// <auto-generated />
namespace ENETCare.IMS.WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddEnetCareUserIdField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEnetCareUserIdField));
        
        string IMigrationMetadata.Id
        {
            get { return "201605020841472_AddEnetCareUserIdField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
